### ISSUE TITLE
Plans on 1.18.2?

### ISSUE THREAD

**Issue by DarkShadow44** [DynamicTreesTeam/DynamicTrees-PHC2#1]
Pam's Harvestcraft Trees for 1.18.2 just got released. How are the chances for a 1.18.2 port?

**Comment by chefexperte** [comment]
We're doing 1.16.5 first, but chances are 1.18.2 might be coming next.

**Comment by Sandrituky** [comment]
Soon anytime? :)

**Comment by supermassimo** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-pams-harvestcraft-2/files/4624048
