### ISSUE TITLE
Port to 1.19.2

### ISSUE THREAD

**Issue by Al3xCalibur** [DynamicTreesTeam/DynamicTrees-PHC2#4]
Hello

First thanks a lot for this compatibility mod, it is really appreciated!
Given the recent porting of DT (still in beta) and DT+ to version 1.19.2, I would like to know if you will have the time lately to do it.

Otherwise, I can help you a bit (I'm not very proficient in creating mods, but much more in Java), at least to make it build and update versions.

**Comment by supermassimo** [comment]
We will gladly accept any help we can get! Please join the discord to know what we are up to https://discord.gg/A4FCBS3

**Comment by Al3xCalibur** [comment]
So here is my first try over migration #5
I've listed everything that was not working.

**Comment by supermassimo** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-pams-harvestcraft-2/files/all?page=1&pageSize=20&version=1.19.2
